In [6]:
! pip install tensorflow

In [5]:
# %matplotlib inline

In [ ]:
'Hello I am %s, %d years old.' % ('Jason', 22)

In [ ]:
'Hello I am %s' % 'Jason'

In [ ]:
import tensorflow as tf

#  建立運算圖
hello = tf.constant('hello world')

# 進行運算
session = tf.Session()
print(session.run(hello))

session.close()

In [ ]:
import tensorflow as tf

hello = tf.constant('hello world')

with tf.Session() as session:
    session.run(hello)

## Ex1: TensorFlow加法

In [ ]:
import tensorflow as tf

# 重設Tensorflow環境
tf.reset_default_graph()

num1a = tf.constant(3)
num1b = tf.constant(3)
result1 = tf.add(num1a, num1b)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result1)
    print(value)

## Tensorflow 增加tensor名稱

3+3

In [ ]:
import tensorflow as tf

# 重設Tensorflow環境
tf.reset_default_graph()

num1a = tf.constant(3, name='1A')
num1b = tf.constant(3, name='1B')
result1 = tf.add(num1a, num1b, name='result1')
print(num1a)
print(num1b)
print(result1)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result1)
    print(value)

## Ex2:  3 += 7
```
 a = 3
 b = 7
 result = a + b
 a = result
```

In [ ]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

num2a = tf.Variable(3)
num2b = tf.constant(7)
result2 = tf.add(num2a, num2b)
assign2 = tf.assign(num2a, result2)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(assign2)
    print(value)
    print('num2a: ', session.run(num2a))

## Ex3: (3 += 1) run 8 times.

In [ ]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

num3a = tf.Variable(3)
num3b = tf.constant(1)
result3 = tf.add(num3a, num3b)
assign3 = tf.assign(num3a, result3)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    for i in range(8):
        value = session.run(assign3)
        print('run: ', i, value)
    print('Finally: ', session.run(num3a))

## Ex4: Shape 矩陣

In [ ]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

# dot 0-D
num4a = tf.constant(1)
print('num4a: ', num4a.shape, 'Type: ', num4a)
# dot 0-D
num4a_ = tf.constant(1, dtype=tf.float32)
print('num4a_: ', num4a_.shape, 'Type: ', num4a_)
# dot 0-D
num4b = tf.ones([]) # 1.0
print('num4b: ', num4b.shape, 'Type: ', num4b)
# 1-D
num4c = tf.ones([1]) # [1.0] Vector
print('num4c: ', num4c.shape, 'Type: ', num4c)
# 1-D
num4d = tf.ones([3]) # [1.0, 1.0, 1.0] Vector
print('num4d: ', num4d.shape)
# 2-D
num4e = tf.ones([3, 2]) # [[1.0, 1.0]]
print('num4e: ', num4e.shape)
# 2-D
# 一維2元素, 二維3元素
num4f = tf.ones([2, 3])
print('num4f: ', num4f.shape)
# [
#    [1.0, 1.0, 1.0],
#    [1.0, 1.0, 1.0]
# ]


## Ex5: 1-Dimensions Operations

In [12]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

num5a = tf.constant([1, 3, 5, 7, 9, 11])
print('num5a: ', num5a.shape, 'Type: ', num5a)
# num5b = tf.constant([3, 5, 7, 9, 11]) is error
num5b = tf.constant([3, 5, 7, 9, 11, 13])
print('num3b: ', num5b.shape, 'Type: ', num5b)
result5a = tf.add(num5a, num5b)


with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result5a)
    print(value)

num5a:  (6,) Type:  Tensor("Const:0", shape=(6,), dtype=int32)
num3b:  (6,) Type:  Tensor("Const_1:0", shape=(6,), dtype=int32)
[ 4  8 12 16 20 24]


In [16]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

num5a = tf.constant([1, 3, 5, 7, 9, 11])
print('num5a: ', num5a.shape, 'Type: ', num5a)
# num5b = tf.constant([3, 5, 7, 9, 11]) is error
num5b = tf.constant([3, 5, 7, 9, 11, 13])
print('num3b: ', num5b.shape, 'Type: ', num5b)

# 0-D(only one element) and 1-D ==> Broadcast
num5c = tf.constant(3) # Broadcast ==> [3, 3, 3, 3, 3, 3]
num5d = tf.constant([3])# Broadcast ==> [3, 3, 3, 3, 3, 3]

result5a = tf.add(num5a, num5b)
result5b = tf.add(num5a, num5c)
result5c = tf.add(num5a, num5d)
result5d = tf.subtract(num5a, num5b) # 相減
result5e = tf.multiply(num5a, num5b) # 相乘
result5f = tf.div(num5a, num5b) # 相除(整數)
result5g = tf.divide(num5a, num5b) # 相除(小數)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result5f)
    print(value)
    value = session.run(result5g)
    print(value)

num5a:  (6,) Type:  Tensor("Const:0", shape=(6,), dtype=int32)
num3b:  (6,) Type:  Tensor("Const_1:0", shape=(6,), dtype=int32)
[0 0 0 0 0 0]
[0.33333333 0.6        0.71428571 0.77777778 0.81818182 0.84615385]


## Ex6: 

In [14]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

matrix6a = tf.constant([[2, 3], [1, 4], [7, 2]])
matrix6b = tf.constant([[1, 4, 7], [3, 6, 9]])

print('matrix6a shape: ', matrix6a.shape)

# 矩陣相乘
# Shape: [A, B] X [B, C] ==> [A, C]
result6 = tf.matmul(matrix6a, matrix6b)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result6)
    print(value)

matrix6a shape:  (3, 2)
[[11 26 41]
 [13 28 43]
 [13 40 67]]
