In [1]:
! pip install tensorflow

In [2]:
# %matplotlib inline

In [3]:
'Hello I am %s, %d years old.' % ('Jason', 22)

'Hello I am Jason, 22 years old.'

In [4]:
'Hello I am %s' % 'Jason'

'Hello I am Jason'

In [5]:
import tensorflow as tf

#  建立運算圖
hello = tf.constant('hello world')

# 進行運算
session = tf.Session()
print(session.run(hello))

session.close()

b'hello world'


In [6]:
import tensorflow as tf

hello = tf.constant('hello world')

with tf.Session() as session:
    session.run(hello)

## Ex1: TensorFlow加法

In [7]:
import tensorflow as tf

# 重設Tensorflow環境
tf.reset_default_graph()

num1a = tf.constant(3)
num1b = tf.constant(3)
result1 = tf.add(num1a, num1b)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result1)
    print(value)

6


## Tensorflow 增加tensor名稱

3+3

In [8]:
import tensorflow as tf

# 重設Tensorflow環境
tf.reset_default_graph()

num1a = tf.constant(3, name='1A')
num1b = tf.constant(3, name='1B')
result1 = tf.add(num1a, num1b, name='result1')
print(num1a)
print(num1b)
print(result1)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result1)
    print(value)

Tensor("1A:0", shape=(), dtype=int32)
Tensor("1B:0", shape=(), dtype=int32)
Tensor("result1:0", shape=(), dtype=int32)
6


## Ex2:  3 += 7
```
 a = 3
 b = 7
 result = a + b
 a = result
```

In [9]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

num2a = tf.Variable(3)
num2b = tf.constant(7)
result2 = tf.add(num2a, num2b)
assign2 = tf.assign(num2a, result2)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(assign2)
    print(value)
    print('num2a: ', session.run(num2a))

10
num2a:  10


## Ex3: (3 += 1) run 8 times.

In [10]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

num3a = tf.Variable(3)
num3b = tf.constant(1)
result3 = tf.add(num3a, num3b)
assign3 = tf.assign(num3a, result3)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    for i in range(8):
        value = session.run(assign3)
        print('run: ', i, value)
    print('Finally: ', session.run(num3a))

run:  0 4
run:  1 5
run:  2 6
run:  3 7
run:  4 8
run:  5 9
run:  6 10
run:  7 11
Finally:  11


## Ex4: Shape 矩陣

In [11]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

# dot 0-D
num4a = tf.constant(1)
print('num4a: ', num4a.shape, 'Type: ', num4a)
# dot 0-D
num4a_ = tf.constant(1, dtype=tf.float32)
print('num4a_: ', num4a_.shape, 'Type: ', num4a_)
# dot 0-D
num4b = tf.ones([]) # 1.0
print('num4b: ', num4b.shape, 'Type: ', num4b)
# 1-D
num4c = tf.ones([1]) # [1.0] Vector
print('num4c: ', num4c.shape, 'Type: ', num4c)
# 1-D
num4d = tf.ones([3]) # [1.0, 1.0, 1.0] Vector
print('num4d: ', num4d.shape)
# 2-D
num4e = tf.ones([3, 2]) # [[1.0, 1.0]]
print('num4e: ', num4e.shape)
# 2-D
# 一維2元素, 二維3元素
num4f = tf.ones([2, 3])
print('num4f: ', num4f.shape)
# [
#    [1.0, 1.0, 1.0],
#    [1.0, 1.0, 1.0]
# ]


num4a:  () Type:  Tensor("Const:0", shape=(), dtype=int32)
num4a_:  () Type:  Tensor("Const_1:0", shape=(), dtype=float32)
num4b:  () Type:  Tensor("ones:0", shape=(), dtype=float32)
num4c:  (1,) Type:  Tensor("ones_1:0", shape=(1,), dtype=float32)
num4d:  (3,)
num4e:  (3, 2)
num4f:  (2, 3)


## Ex5: 1-Dimensions Operations

In [12]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

num5a = tf.constant([1, 3, 5, 7, 9, 11])
print('num5a: ', num5a.shape, 'Type: ', num5a)
# num5b = tf.constant([3, 5, 7, 9, 11]) is error
num5b = tf.constant([3, 5, 7, 9, 11, 13])
print('num3b: ', num5b.shape, 'Type: ', num5b)
result5a = tf.add(num5a, num5b)


with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result5a)
    print(value)

num5a:  (6,) Type:  Tensor("Const:0", shape=(6,), dtype=int32)
num3b:  (6,) Type:  Tensor("Const_1:0", shape=(6,), dtype=int32)
[ 4  8 12 16 20 24]


In [13]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

num5a = tf.constant([1, 3, 5, 7, 9, 11])
print('num5a: ', num5a.shape, 'Type: ', num5a)
# num5b = tf.constant([3, 5, 7, 9, 11]) is error
num5b = tf.constant([3, 5, 7, 9, 11, 13])
print('num3b: ', num5b.shape, 'Type: ', num5b)

# 0-D(only one element) and 1-D ==> Broadcast
num5c = tf.constant(3) # Broadcast ==> [3, 3, 3, 3, 3, 3]
num5d = tf.constant([3])# Broadcast ==> [3, 3, 3, 3, 3, 3]

result5a = tf.add(num5a, num5b)
result5b = tf.add(num5a, num5c)
result5c = tf.add(num5a, num5d)
result5d = tf.subtract(num5a, num5b) # 相減
result5e = tf.multiply(num5a, num5b) # 相乘
result5f = tf.div(num5a, num5b) # 相除(整數)
result5g = tf.divide(num5a, num5b) # 相除(小數)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result5f)
    print(value)
    value = session.run(result5g)
    print(value)

num5a:  (6,) Type:  Tensor("Const:0", shape=(6,), dtype=int32)
num3b:  (6,) Type:  Tensor("Const_1:0", shape=(6,), dtype=int32)
[0 0 0 0 0 0]
[0.33333333 0.6        0.71428571 0.77777778 0.81818182 0.84615385]


## Ex6: Matrix

In [14]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

matrix6a = tf.constant([[2, 3], [1, 4], [7, 2]])
matrix6b = tf.constant([[1, 4, 7], [3, 6, 9]])

print('matrix6a shape: ', matrix6a.shape)

# 矩陣相乘
# Shape: [A, B] X [B, C] ==> [A, C]
result6 = tf.matmul(matrix6a, matrix6b)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer())
    value = session.run(result6)
    print(value)

matrix6a shape:  (3, 2)
[[11 26 41]
 [13 28 43]
 [13 40 67]]


## Ex7: Matrix reshape

In [16]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

matrix7a = tf.constant([1, 3, 7, 4, 9, 13, 17, 23])
matrix7b = tf.reshape(matrix7a, [4, 2])
matrix7c = tf.reshape(matrix7a, [2, 4])
matrix7d = tf.reshape(matrix7a, [8, 1])
matrix7e = tf.reshape(matrix7a, [1, 8])

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer()) # len == 8
    print('matrix7b: ', session.run(matrix7b)) # 4 x 2
    print('matrix7c: ', session.run(matrix7c)) # 2 x 4
    print('matrix7d: ', session.run(matrix7d)) # 8 x 1
    print('matrix7e: ', session.run(matrix7e)) # 1 x 8

matrix7b:  [[ 1  3]
 [ 7  4]
 [ 9 13]
 [17 23]]
matrix7c:  [[ 1  3  7  4]
 [ 9 13 17 23]]
matrix7d:  [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [ 9]
 [13]
 [17]
 [23]]
matrix7e:  [[ 1  3  7  4  9 13 17 23]]


In [17]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

matrix7a = tf.constant([1, 3, 7, 4, 9, 13, 17, 23])
matrix7c = tf.reshape(matrix7a, [2, 4])
matrix7f = tf.reshape(matrix7a, [-1])

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer()) # len == 8
    print('matrix7f: ', session.run(matrix7f)) # 扁平化(展開)

matrix7f:  [ 1  3  7  4  9 13 17 23]


## Ex8: Placeholder

In [23]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

matrix8a = tf.constant([1, 3, 7, 4, 9, 13, 17, 23])
placeholder8b = tf.placeholder(tf.int32, [8])

result8a = tf.multiply(matrix8a, placeholder8b)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer()) # len == 8
    print('result8a: ',
          # 訓練模型時透過placeholder替換資料訓練
          session.run(result8a, feed_dict={placeholder8b: [2, 4, 7, 1, 9, 11, 13, 15]})
         )

result8a:  [  2  12  49   4  81 143 221 345]


In [24]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

matrix8a = tf.constant([1, 3, 7, 4, 9, 13, 17, 23])
placeholder8b = tf.placeholder(tf.int32, [8])
placeholder8c = tf.placeholder(tf.int32, [8])

result8a = tf.multiply(matrix8a, placeholder8b)
result8b = tf.multiply(result8a, placeholder8c)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer()) # len == 8
    print('result8a: ',
          # 訓練模型時透過placeholder替換資料訓練
          session.run(result8b, feed_dict={
              placeholder8b: [2, 4, 7, 1, 9, 11, 13, 15],
              placeholder8c: [6, 2, 2, 3, 8, 21, 5, 111],
          })
         )

result8a:  [   12    24    98    12   648  3003  1105 38295]


In [25]:
import tensorflow as tf
# 重設Tensorflow環境
tf.reset_default_graph()

matrix8a = tf.constant([1, 3, 7, 4, 9, 13, 17, 23])
placeholder8b = tf.placeholder(tf.int32, [8])
placeholder8c = tf.placeholder(tf.int32, [8])
placeholder8d = tf.placeholder(tf.int32, [None])

result8a = tf.multiply(matrix8a, placeholder8b)
result8b = tf.multiply(result8a, placeholder8c)
result8c = tf.multiply(result8b, placeholder8d)

with tf.Session() as session:
    # 全域變數初始化
    session.run(tf.global_variables_initializer()) # len == 8
    print('result8a: ',
          # 訓練模型時透過placeholder替換資料訓練
          session.run(result8c, feed_dict={
              placeholder8b: [2, 4, 7, 1, 9, 11, 13, 15],
              placeholder8c: [6, 2, 2, 3, 8, 21, 5, 111],
              placeholder8d: [2],# 自動擴展
          })
         )

result8a:  [   24    48   196    24  1296  6006  2210 76590]
